USE [master]
GO

/****** Object:  Database [Papeleria]    Script Date: 17/11/2023 02:14:14 a. m. ******/
CREATE DATABASE [Papeleria]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Papeleria', FILENAME = N'E:\SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Papeleria.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Papeleria_log', FILENAME = N'E:\SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Papeleria_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Papeleria].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Papeleria] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Papeleria] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Papeleria] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Papeleria] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Papeleria] SET ARITHABORT OFF 
GO

ALTER DATABASE [Papeleria] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Papeleria] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Papeleria] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Papeleria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Papeleria] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Papeleria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Papeleria] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Papeleria] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Papeleria] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Papeleria] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Papeleria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Papeleria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Papeleria] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Papeleria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Papeleria] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Papeleria] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Papeleria] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Papeleria] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Papeleria] SET  MULTI_USER 
GO

ALTER DATABASE [Papeleria] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Papeleria] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Papeleria] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Papeleria] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Papeleria] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Papeleria] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Papeleria] SET QUERY_STORE = ON
GO

ALTER DATABASE [Papeleria] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Papeleria] SET  READ_WRITE 
GO


